################################################################################
# Module setup
## [module]
################################################################################
# see
# https://gohugo.io/hugo-modules/configuration/#module-config-imports
################################################################################
[[imports]]
path = "github.com/davidsneighbour/components/favicon"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/components/netlification"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/garuda"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/testcontent/aesops-fables"
disabled = false
